### PR TITLE
Add user agent

### PR DESCRIPTION
**Pull request by nataliecarey**
Adding a configurable User Agent String (with default and standard setter/getter) for outgoing requests.

### CODE REVIEW

**Comment by nataliecarey** [comment]
For testing, inside the root of the project (with this branch):

```
node -e 'require("http").createServer(function (req, res) {res.end();console.log("User Agent:", req.headers["user-agent"]);}).listen(8001); var fastImg = require("./main"); fastImg.info("http://localhost:8001/abc"); fastImg.userAgent("Some nice user agent"); fastImg.info("http://localhost:8001/abc");'
```

Example output:

```
User Agent: Fast Image - Node Image Lookup - https://www.npmjs.com/package/fastimage
User Agent: Some nice user agent
```

(then exit with `ctrl+c`)

**Comment by nataliecarey** [comment]
@ShogunPanda any news on this one?  I'm just rolling off the project that inspired the PR and they're currently using my fork as an NPM dependency.  I'd love to get them back onto the official releases before rolling off.

I've implemented following the patterns already laid out with full test coverage, and it resolves the issues currently experienced running the tests against master branch.

**Comment by ShogunPanda** [comment]
Hi @matcarey!
Sorry, I've been busy these days. Will review and merge it soon.

**Comment by nataliecarey** [comment]
No worries, thanks.

**Comment by ShogunPanda** [comment]
I just published 1.1.1. Differently from your propose, setting UserAgent to `null` will just remove the header.
Thanks for your commit!

**Comment by nataliecarey** [comment]
Makes sense, it allows people to opt into the old behaviour.

**Pull request merged**
